import * as Lucide from "lucide-react";

export type IconType = Lucide.LucideIcon;

export const Icono = {
  Inicio: Lucide.Home,
  Clientes: Lucide.Users,
  Pagos: Lucide.DollarSign,
  Contratos: Lucide.FileText,
  Proyectos: Lucide.FolderKanban,
  Contactos: Lucide.Contact,
  Calendario: Lucide.Calendar,
  Alert: Lucide.AlertTriangle,
  Configuracion: Lucide.Settings,
  IA: Lucide.Sparkles,
  Logout: Lucide.LogOut,
  ChevronDown: Lucide.ChevronDown,
  ChevronUp: Lucide.ChevronUp,
  ChevronLeft: Lucide.ChevronLeft,
  ChevronRight: Lucide.ChevronRight,
  Menu: Lucide.Menu,
  Check: Lucide.Check,
  Close: Lucide.X,
  Search: Lucide.Search,
  Eye: Lucide.Eye,
  EyeOff: Lucide.EyeOff,
  User: Lucide.User,
  Plus: Lucide.Plus,
  Trash: Lucide.Trash2,
  Edit: Lucide.Edit2,
  File: Lucide.File,
  Upload: Lucide.Upload,
  Globe: Lucide.Globe,
  Bell: Lucide.Bell,
  Activity: Lucide.Activity,
  History: Lucide.History,
  TrendingUp: Lucide.TrendingUp,
  TrendingDown: Lucide.TrendingDown,
  Info: Lucide.Info,
  Clock: Lucide.Clock,
  Sparkles: Lucide.Sparkles,
  Phone: Lucide.Phone,
  Mail: Lucide.Mail,
  MapPin: Lucide.MapPin,
  Lock: Lucide.Lock,
};
